# Generated by Django 3.1.2 on 2020-11-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(choices=[('Road', 'Road'), ('Hybrid', 'Hybrid'), ('Mountain', 'Mountain'), ('BMX', 'BMX'), ('Childrens', 'Childrens'), ('Other', 'Other')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(choices=[('Carbon Fiber', 'Carbon Fiber'), ('Steel', 'Steel'), ('Titanium', 'Titanium'), ('Aluminum', 'Aluminum'), ('Other', 'Other')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HandlebarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handlebar_type', models.CharField(choices=[('Flat', 'Flat'), ('Riser', 'Riser'), ('Drop', 'Drop'), ('Bullhorn', 'Bullhorn'), ('Aero', 'Aero'), ('Cruiser', 'Cruiser'), ('Butterfly', 'Butterfly'), ('Other', 'Other')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='wheel_size',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)]),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.biketype'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='frame_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.frametype'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='handlebar_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.handlebartype'),
        ),
    ]
