# Generated by Django 3.1.2 on 2020-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='wheel_size',
        ),
        migrations.AddField(
            model_name='bike',
            name='frame_size',
            field=models.CharField(choices=[('XXS', 'XX Small'), ('XS', 'X Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X Large'), ('XXL', 'XX Large'), ('XXXL', 'XXX Large')], default='Small', max_length=15),
        ),
    ]
