# Generated by Django 3.1.2 on 2020-12-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20201212_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='frame_size',
            field=models.CharField(choices=[('XX Small', 'XX Small'), ('X Small', 'X Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X Large', 'X Large'), ('XX Large', 'XX Large'), ('XXX Large', 'XXX Large')], default='Small', max_length=15),
        ),
    ]
