# Generated by Django 3.1.2 on 2020-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20201108_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
