# Generated by Django 3.1.2 on 2020-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('Basic', 'Basic'), ('A', 'Advanced'), ('P', 'Premium')], max_length=15)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
