# Generated by Django 3.1.2 on 2020-12-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Premium', 'Premium')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('level_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.level')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
