# Generated by Django 3.1.2 on 2020-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='services',
            name='total_reviews',
        ),
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(max_length=15),
        ),
    ]
