# Generated by Django 3.1.2 on 2020-11-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201101_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Premium', 'Premium')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='level_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.level'),
        ),
    ]
