# Generated by Django 3.1.2 on 2020-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('level_type', '-rating'), 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='level_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('A', 'Advanced'), ('P', 'Premium')], max_length=15),
        ),
    ]
