# Generated by Django 3.1.2 on 2020-12-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201208_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('reviewed_level_type',), 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='level_type',
            new_name='reviewed_level_type',
        ),
    ]
