# Generated by Django 3.1.2 on 2020-11-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201101_1949'),
        ('reviews', '0003_auto_20201101_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='level_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
