# Generated by Django 3.1.2 on 2020-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20201106_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='level_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Premium', 'Premium')], max_length=15),
        ),
    ]
