# Generated by Django 3.1.2 on 2020-11-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201101_1949'),
        ('reviews', '0005_auto_20201106_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='level_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
