# Generated by Django 3.1.2 on 2020-10-24 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80)),
                ('message', models.TextField()),
                ('date_of_contact', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
