# Generated by Django 3.1.2 on 2020-11-01 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date_of_contact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
