# Generated by Django 3.1.2 on 2020-11-07 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_line_one', models.CharField(blank=True, max_length=80)),
                ('street_address_line_two', models.CharField(blank=True, max_length=80)),
                ('street_address_line_three', models.CharField(blank=True, max_length=80)),
                ('town_or_city', models.CharField(blank=True, max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('contact_by_phone', models.BooleanField(blank=True, default=False)),
                ('bikes', models.ManyToManyField(blank=True, to='bike.Bike')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
