# Generated by Django 3.1.2 on 2020-12-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20201208_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
